name: Publish image to docker hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        docker build . -t shayfeld/devsecopsgames:latest
    - name: publish
      run: |
        docker push shayfeld/devsecopsgames:latest